// <auto-generated />
using System;
using MediCore.Billing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediCore.Billing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("medicore_billing")
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediCore.Billing.Application.Entities.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime?>("FinalizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PricingIssue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("RequiresManualPricing")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InvoiceId");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_invoices_appointment_id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_invoices_invoice_number");

                    b.HasIndex("PatientId", "IssuedAtUtc")
                        .HasDatabaseName("ix_invoices_patient_issued_at");

                    b.ToTable("invoices", "medicore_billing");
                });

            modelBuilder.Entity("MediCore.Billing.Application.Entities.InvoiceLine", b =>
                {
                    b.Property<Guid>("InvoiceLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TariffId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("InvoiceLineId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_lines", "medicore_billing");
                });

            modelBuilder.Entity("MediCore.Billing.Application.Entities.ProcessedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceTopic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MessageId")
                        .HasName("pk_processed_messages");

                    b.HasIndex("ConsumerGroup", "ProcessedAtUtc")
                        .HasDatabaseName("ix_processed_messages_consumer_processed_at");

                    b.ToTable("processed_messages", "medicore_billing");
                });

            modelBuilder.Entity("MediCore.Billing.Application.Entities.ServiceTariff", b =>
                {
                    b.Property<Guid>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("TariffId");

                    b.HasIndex("ServiceCode", "EffectiveFromUtc")
                        .IsUnique()
                        .HasDatabaseName("ux_service_tariffs_code_effective_from");

                    b.ToTable("service_tariffs", "medicore_billing");

                    b.HasData(
                        new
                        {
                            TariffId = new Guid("8b4dcd4c-3cee-4fe6-a3d2-36c90cb0dd01"),
                            Currency = "LKR",
                            Description = "General consultation",
                            EffectiveFromUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ServiceCode = "GEN-CONSULT",
                            UnitPrice = 2500m
                        },
                        new
                        {
                            TariffId = new Guid("8b4dcd4c-3cee-4fe6-a3d2-36c90cb0dd02"),
                            Currency = "LKR",
                            Description = "Specialist consultation",
                            EffectiveFromUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ServiceCode = "SPEC-CONSULT",
                            UnitPrice = 5000m
                        },
                        new
                        {
                            TariffId = new Guid("8b4dcd4c-3cee-4fe6-a3d2-36c90cb0dd03"),
                            Currency = "LKR",
                            Description = "Follow-up consultation",
                            EffectiveFromUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ServiceCode = "FOLLOW-UP",
                            UnitPrice = 1500m
                        });
                });

            modelBuilder.Entity("MediCore.Billing.Application.Entities.InvoiceLine", b =>
                {
                    b.HasOne("MediCore.Billing.Application.Entities.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("MediCore.Billing.Application.Entities.Invoice", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
